#!/bin/bash

#Leer todo el archivo, luego reemplazar toda la linea y la linea de abajo con "devDependencies": {
#Así quitar la coma
#sed -i ':a;N;$!ba;s/,\n.."devDependencies":.{/\n"devDependencies": {/g' package.json
#Se elimina devDependencies hasta que choque con el caracter }
sed -i '/"devDependencies": {/,/}/d' package.json
#estrategia alternativa, elimina /},\n}/
sed -i ':a;N;$!ba;s/},\n}/}\n}/g' package.json

rm -f package-lock.json
rm -rf node_modules
cat package.json
