#!/bin/bash

#Leer todo el archivo, luego reemplazar toda la linea
#Así quitar la coma
sed ':a;N;$!ba;s/,\n.."devDependencies":.{/"devDependencies": {/g' package.json
#Se elimina devDependencies hasta que choque con el caracter }
sed '/"devDependencies": {/,/}/d' package.json
rm -f package-lock.json
rm -rf node_modules
cat package.json
