#!/bin/bash
echo "============================================================="
echo "          ESTRUCTURA DE TRAVIS Y DIRECTORIOS                 "
echo "============================================================="
ls -lha ..
echo "..."
ls -lha ../.cache
echo "..."
ls -lha $HOME/.cache

echo "============================================================="
echo "          ESTRUCTURA APLICACIÓN FRONTEND                     "
echo "============================================================="
ls -lha dist

echo "============================================================="
echo "      GENERAR ESTRUCTURA APLICACIÓN BACKEND                  "
echo "============================================================="
mkdir -p public && cp -r dist/ ./public/
cp server/server.js .
ls -lha

echo "============================================================="
